import { readdir } from 'node:fs/promises';
import { $ } from 'bun';

const SOURCE_LOCALE = 'en';
const TARGET_LOCALES = ['ru'];

const LOCALES_DIR = 'packages/i18n/src/locales';
const GENERATED_PATH = 'packages/i18n/src/generated/keys.ts';

type MessageTree = { [segment: string]: string | MessageTree };

function collectInto(target: Map<string, string>, prefix: string, tree: MessageTree): void {
  for (const [segment, value] of Object.entries(tree)) {
    const path = `${prefix}.${segment}`;
    if (typeof value === 'string') {
      target.set(path, value);
      continue;
    }
    collectInto(target, path, value);
  }
}

async function readNamespaces(locale: string): Promise<string[]> {
  const entries = await readdir(`${LOCALES_DIR}/${locale}`);
  return entries
    .filter((entry) => entry.endsWith('.json'))
    .map((entry) => entry.slice(0, -'.json'.length))
    .sort();
}

async function readLocale(locale: string): Promise<Map<string, string>> {
  const messages = new Map<string, string>();
  for (const namespace of await readNamespaces(locale)) {
    const tree: MessageTree = await Bun.file(`${LOCALES_DIR}/${locale}/${namespace}.json`).json();
    collectInto(messages, namespace, tree);
  }
  return messages;
}

function report(title: string, keys: string[]): void {
  if (keys.length === 0) return;
  console.error(`\n${title}`);
  for (const key of keys) console.error(`  ${key}`);
}

function renderKeyUnion(keys: string[]): string {
  const members = keys.map((key) => `  '${key}',`).join('\n');
  return `// Generated by \`bun run i18n:check\` from the ${SOURCE_LOCALE} locale resources. Do not edit.

export const TRANSLATION_KEYS = [
${members}
] as const;

export type TranslationKey = (typeof TRANSLATION_KEYS)[number];

declare global {
  namespace FormatjsIntl {
    interface Message {
      ids: TranslationKey;
    }
  }
}
`;
}

const source = await readLocale(SOURCE_LOCALE);
let hasParityFailure = false;

for (const locale of TARGET_LOCALES) {
  const target = await readLocale(locale);
  const missing = [...source.keys()].filter((key) => !target.has(key)).sort();
  const orphaned = [...target.keys()].filter((key) => !source.has(key)).sort();

  report(`Missing in ${locale} (present in ${SOURCE_LOCALE}):`, missing);
  report(`Orphaned in ${locale} (absent from ${SOURCE_LOCALE}):`, orphaned);
  hasParityFailure ||= missing.length > 0 || orphaned.length > 0;
}

if (hasParityFailure) {
  console.error(`\nEvery key exists in ${SOURCE_LOCALE} and every target locale, or neither.`);
  process.exit(1);
}

const generated = Bun.file(GENERATED_PATH);
const before = (await generated.exists()) ? await generated.text() : '';

await Bun.write(GENERATED_PATH, renderKeyUnion([...source.keys()].sort()));
await $`bunx biome format --write ${GENERATED_PATH}`.quiet();

const after = await Bun.file(GENERATED_PATH).text();

if (before !== after) {
  console.error(`\n${GENERATED_PATH} was regenerated — commit it.`);
  process.exit(1);
}

console.log(`${source.size} keys, ${[SOURCE_LOCALE, ...TARGET_LOCALES].join(' + ')} in parity.`);
