import { readdir, readFile, writeFile } from 'node:fs/promises';
import { simplifyIconPath } from './weapon-icons/simplify';

/**
 * The two sets, and they are two because their *ids* answer to different things. A weapon icon is
 * named in Counter-Strike's internal weapon vocabulary, which is what `Kill.weapon` carries, so
 * `@disa/demo-core` can hold that table to its word. Armour is not in any demo vocabulary — it is
 * `TickTrack.armour` and the `FLAG_HELMET` bit read together — so its ids belong to the interface
 * that draws them, and `demo-core` stays out of it (hard rule 11).
 */
const SETS = [
  {
    assetDir: 'apps/web/assets/weapon-icons',
    outputPath: 'apps/web/src/core/glyphs/generated/weapon-icons.ts',
    typeName: 'WeaponIcon',
    tableName: 'WEAPON_ICONS',
    idImport: "import type { WeaponIconId } from '@disa/demo-core';",
    idType: 'WeaponIconId',
    tableDoc: `/**
 * Every weapon \`@disa/demo-core\` can name an icon for. The record is keyed by \`WeaponIconId\`, so an
 * id the vocabulary tables name and nobody shipped is a compile error rather than an empty glyph.
 */`,
  },
  {
    assetDir: 'apps/web/assets/equipment-icons',
    outputPath: 'apps/web/src/core/glyphs/generated/equipment-icons.ts',
    typeName: 'EquipmentIcon',
    tableName: 'EQUIPMENT_ICONS',
    idImport: "import type { EquipmentIconId } from '../helpers/equipment';",
    idType: 'EquipmentIconId',
    tableDoc: `/**
 * The two armour states Counter-Strike draws: the vest alone, and the vest with the helmet beside
 * it. Keyed by \`EquipmentIconId\`, so an asset nobody names and an id nobody shipped are both a
 * compile error.
 */`,
  },
] as const;

/**
 * In the icons' own units, whose box is 32 tall. At the sizes §5.3 and §5.4 draw one — 10px of
 * height — this is a thirtieth of a pixel, and it takes the shipped table from 506 kB of Valve's
 * curves to 25 kB of polygons.
 */
const TOLERANCE = 0.3;
const DECIMALS = 1;

function fail(message: string): never {
  console.error(message);
  process.exit(1);
}

function attribute(source: string, name: string, id: string): string {
  const match = source.match(new RegExp(`\\s${name}="([^"]+)"`));
  if (match?.[1] === undefined) fail(`${id}: no ${name}`);

  return match[1];
}

function viewBox(source: string, id: string): { width: number; height: number } {
  const parts = attribute(source, 'viewBox', id).trim().split(/\s+/).map(Number);
  const [minX, minY, width, height] = parts;
  if (parts.length !== 4 || minX !== 0 || minY !== 0 || !width || !height)
    fail(`${id}: viewBox is not "0 0 <width> <height>"`);

  return { width, height };
}

function allPaths(source: string, id: string): string {
  /* Every outline in the asset, joined into one `d` as subpaths. Valve draws the vest and the
     helmet as two siblings in one 48.75-wide box, and a rule of "exactly one path" would have
     rejected that asset — the rule this replaces took the *first* path and silently lost the rest,
     which is the worse of the two failures. Joining is safe for this art specifically: it carries
     no `transform`, no `fill-rule` and no per-path fill, checked before it was committed, so the
     subpaths compose exactly as the siblings did. */
  const matches = [...source.matchAll(/\sd="([^"]+)"/g)].map((match) => match[1] ?? '');
  if (matches.length === 0) fail(`${id}: no paths`);

  return matches.join(' ');
}

async function readIcon(assetDir: string, file: string): Promise<{ id: string; entry: string }> {
  const id = file.replace(/\.svg$/, '');
  const source = await readFile(`${assetDir}/${file}`, 'utf8');

  const { width, height } = viewBox(source, id);
  const d = simplifyIconPath(allPaths(source, id), TOLERANCE, DECIMALS);
  if (d === '') fail(`${id}: the outline simplified to nothing`);

  return {
    id,
    entry: `  ${id}: {\n    width: ${width},\n    height: ${height},\n    d: '${d}',\n  },`,
  };
}

for (const set of SETS) {
  const files = (await readdir(set.assetDir)).filter((file) => file.endsWith('.svg')).sort();
  if (files.length === 0) fail(`${set.assetDir} holds no icons`);

  const icons = await Promise.all(files.map((file) => readIcon(set.assetDir, file)));

  const output = `// Generated by \`bun run icons:generate\` from ${set.assetDir}.
// Valve owns these outlines; replace the assets and regenerate, never edit this file.

${set.idImport}

export interface ${set.typeName} {
  /**
   * The icon's own box. A caller sets the height and lets the width follow, which is how
   * Counter-Strike draws these and why a pistol is narrow rather than short.
   */
  readonly width: number;
  readonly height: number;
  /** Polygons, even-odd filled — simplified at ${TOLERANCE} of the box's 32 units. */
  readonly d: string;
}

${set.tableDoc}
export const ${set.tableName}: Readonly<Record<${set.idType}, ${set.typeName}>> = {
${icons.map((icon) => icon.entry).join('\n')}
};
`;

  await writeFile(set.outputPath, output);
  console.log(`${set.outputPath}: ${icons.length} icons, ${output.length} bytes`);
}
