import { PNG } from 'pngjs';
import {
  MAP_IDS,
  MAP_OVERVIEWS,
  type MapId,
  RADAR_IMAGE_SIZE,
} from '../../packages/map-data/src/generated/overviews';
import { plateLevelIndex } from '../../packages/map-data/src/layout';
import { NAV_OVERRIDES } from '../../packages/map-data/src/navgrid-overrides';
import { mapSpawns } from '../../packages/map-data/src/spawns';
import { radarX, radarY } from '../../packages/map-data/src/transform';
import { applyRects, keepComponents, packBits, traceLevel } from './navgrid/trace';

/**
 * Traces a walkable grid per map level from the vanilla radar images.
 *
 *     bun run navgrid:generate
 *     DISALYTICS_NAVGRID_DEBUG=<dir> bun run navgrid:generate     # also writes a mask-over-radar PNG per level
 *
 * 4 px cells (256 x 256 over the 1024 px image) with walls grown by 2 px: at 8 px cells a narrow
 * doorway lost its cells to the 50% share rule and split Anubis, Overpass and Nuke's lower floor;
 * 4 px keeps them joined. Hand corrections are `navgrid-overrides.ts`.
 */
const PACKAGE_DIR = 'packages/map-data';
const VANILLA_DIR = `${PACKAGE_DIR}/assets/radar/vanilla`;
const OUTPUT_DIR = `${PACKAGE_DIR}/src/generated/navgrids`;
const DEBUG_ENV = 'DISALYTICS_NAVGRID_DEBUG';
const CELL = 4;
const ERODE = 2;
/** A component this share of the largest, or smaller but holding a spawn, is kept. */
const MIN_SHARE = 0.02;
const SPAWN_REACH = 8;

/** The nearest walkable cell to `(sx, sy)` within `SPAWN_REACH`, or -1. */
function nearestWalkable(grid: Uint8Array, cells: number, sx: number, sy: number): number {
  for (let r = 0; r <= SPAWN_REACH; r++) {
    for (let dy = -r; dy <= r; dy++) {
      for (let dx = -r; dx <= r; dx++) {
        const x = sx + dx;
        const y = sy + dy;
        const inside = x >= 0 && y >= 0 && x < cells && y < cells;
        if (inside && grid[y * cells + x] === 1) return y * cells + x;
      }
    }
  }
  return -1;
}

function seedsFor(id: MapId, levelIndex: number, grid: Uint8Array, cells: number): number[] {
  const overview = MAP_OVERVIEWS[id];
  const spawns = [...mapSpawns(id, 'T'), ...mapSpawns(id, 'CT')];

  return spawns
    .filter((spawn) => plateLevelIndex(overview, spawn.z) === levelIndex)
    .map((spawn) =>
      nearestWalkable(
        grid,
        cells,
        Math.floor(radarX(overview, spawn.x) / CELL),
        Math.floor(radarY(overview, spawn.y) / CELL),
      ),
    )
    .filter((seed) => seed >= 0);
}

type Rgb = [number, number, number];

function tinted(r: number, g: number, b: number, a: number, walk: boolean): Rgb {
  if (walk) return [r * 0.5, g * 0.5 + 128, b * 0.5];
  return a >= 200 ? [r * 0.4 + 150, g * 0.4, b * 0.4] : [255, 255, 255];
}

/** The level's mask laid over its radar: walkable green, traced-out floor red, void white. */
function debugImage(png: PNG, grid: Uint8Array, size: number): Buffer {
  const out = new PNG({ width: png.width, height: png.height });
  for (let y = 0; y < png.height; y++) {
    for (let x = 0; x < png.width; x++) {
      const i = (y * png.width + x) * 4;
      const walk = grid[Math.floor(y / CELL) * size + Math.floor(x / CELL)] === 1;
      const [r, g, b] = tinted(
        png.data[i] ?? 0,
        png.data[i + 1] ?? 0,
        png.data[i + 2] ?? 0,
        png.data[i + 3] ?? 0,
        walk,
      );
      out.data[i] = Math.round(r);
      out.data[i + 1] = Math.round(g);
      out.data[i + 2] = Math.round(b);
      out.data[i + 3] = 255;
    }
  }
  return PNG.sync.write(out);
}

function render(levels: string[], size: number): string {
  return [
    '// Generated by `bun run navgrid:generate` from the vanilla radar images and navgrid-overrides.ts.',
    '// Traced from a picture, not a nav mesh. Edit the overrides, not this file.',
    '',
    "import type { NavGridData } from '../../types';",
    '',
    'export const NAV_GRID: NavGridData = {',
    `  cell: ${CELL},`,
    `  size: ${size},`,
    '  levels: [',
    ...levels.map((level) => `    '${level}',`),
    '  ],',
    '};',
    '',
  ].join('\n');
}

async function traceMap(id: MapId, debugDir: string | undefined): Promise<string[]> {
  const overview = MAP_OVERVIEWS[id];
  const size = RADAR_IMAGE_SIZE / CELL;
  const levels: string[] = [];

  for (const [levelIndex, level] of overview.levels.entries()) {
    const file = Bun.file(`${VANILLA_DIR}/${level.image}.png`);
    const png = PNG.sync.read(Buffer.from(await file.arrayBuffer()));
    if (png.width !== RADAR_IMAGE_SIZE || png.height !== RADAR_IMAGE_SIZE) {
      throw new Error(
        `${level.image}.png is ${png.width}x${png.height}, expected ${RADAR_IMAGE_SIZE}`,
      );
    }

    const traced = traceLevel(png.data, RADAR_IMAGE_SIZE, { cell: CELL, erode: ERODE });
    for (const override of NAV_OVERRIDES[id] ?? []) {
      if (override.level !== levelIndex) continue;
      applyRects(traced, size, CELL, override.open, 1);
      applyRects(traced, size, CELL, override.close, 0);
    }

    const seeds = seedsFor(id, levelIndex, traced, size);
    const grid = keepComponents(traced, size, seeds, MIN_SHARE);
    levels.push(Buffer.from(packBits(grid)).toString('base64'));

    if (debugDir !== undefined) {
      await Bun.write(`${debugDir}/${level.image}.png`, debugImage(png, grid, size));
    }
  }

  return levels;
}

const debugDir = process.env[DEBUG_ENV];

for (const id of MAP_IDS) {
  const levels = await traceMap(id, debugDir);
  await Bun.write(`${OUTPUT_DIR}/${id}.ts`, render(levels, RADAR_IMAGE_SIZE / CELL));
  console.log(`${OUTPUT_DIR}/${id}.ts: ${levels.length} level(s).`);
}
