import { readFileSync } from 'node:fs';
import { writeFile } from 'node:fs/promises';
import { gzipSync } from 'node:zlib';
import type { MatchEvents, MatchHeader, ParsedDemo, TickTrack } from '@disa/demo-core';
import { byteLengthOf, encodeDemo } from '@disa/demo-store/codec';
import {
  SAMPLE_MATCHES,
  type SampleMatch,
} from '../../apps/web/src/core/samples/helpers/catalogue';

const GLUE_PATH = '../../crates/demo-parser-wasm/pkg/demo_parser_wasm.js';
const BINARY_PATH = 'crates/demo-parser-wasm/pkg/demo_parser_wasm_bg.wasm';

/**
 * The glue is generated into a gitignored `pkg/`, so it cannot be a typed static import — a fresh
 * clone has to typecheck before any binary exists, which is the same reason `wasm-smoke.ts` loads
 * it this way. The shape is declared here rather than trusted: what it claims is checked by
 * `encodeDemo` refusing anything that is not a `ParsedDemo`.
 */
interface DemoBufferLike {
  push(chunk: Uint8Array): void;
}

interface ParserGlue {
  default: (init: { module_or_path: Uint8Array }) => Promise<unknown>;
  DemoBuffer: new (sizeBytes: number) => DemoBufferLike;
  parseDemo: (
    demo: DemoBufferLike,
    onPass: (completedPasses: number) => void,
    onHeader: (header: MatchHeader) => void,
  ) => { track: TickTrack; events: MatchEvents };
}

/**
 * Rebuilds the containers behind `SAMPLE_MATCHES` from local `.dem` files.
 *
 * The demos themselves are never committed — `AGENTS.md`'s constraints table — so this needs the
 * directory they live in, and it is the owner's machine that has them:
 *
 *     DISALYTICS_SAMPLE_DIR=~/Documents/<the series> bun run samples:generate
 *
 * It must be run again whenever `SCHEMA_VERSION` moves, and `bun run samples:check` is what fails
 * the build until it has been. Byte-stable across runs: the parse is deterministic by hard rule 8
 * and the gzip carries no timestamp.
 */
const ASSET_DIR = 'apps/web/assets/samples';
const SOURCE_ENV = 'DISALYTICS_SAMPLE_DIR';
const GENERATED_PATH = 'apps/web/src/core/samples/generated/assets.ts';

/** No `mtime`, no name, no OS byte — the same bytes twice, which is what makes a rebuild a no-op. */
const GZIP: Parameters<typeof gzipSync>[1] = { level: 9, ...({ mtime: 0 } as object) };

async function parseFile(glue: ParserGlue, path: string): Promise<ParsedDemo> {
  const file = Bun.file(path);
  const demo = new glue.DemoBuffer(file.size);
  const reader = file.stream().getReader();

  for (;;) {
    const chunk = await reader.read();
    if (chunk.done) break;
    demo.push(chunk.value);
  }

  let header: MatchHeader | undefined;
  const { track, events } = glue.parseDemo(
    demo,
    () => {},
    (read: MatchHeader) => {
      header = read;
    },
  );

  if (header === undefined) throw new Error(`${path} produced no header`);

  return { header, track, events };
}

function flatten(chunks: readonly Uint8Array[]): Uint8Array {
  const bytes = new Uint8Array(byteLengthOf(chunks));
  let at = 0;

  for (const chunk of chunks) {
    bytes.set(chunk, at);
    at += chunk.byteLength;
  }

  return bytes;
}

const GENERATED_DOC = `/**
 * Where each sample's bytes are, and how big they are on the wire — written by
 * \`bun run samples:generate\`, and held to the files on disk by \`bun run samples:check\`.
 *
 * The URL is Vite's: a container is imported with \`?url\`, so it is emitted into \`/assets/\` with a
 * content hash and served under the \`immutable\` rule in \`apps/web/public/_headers\` like every other
 * hashed asset. It is **not** in the service worker's precache — \`globPatterns\` is \`html,css,js\` —
 * which is what keeps a reader who came with their own demo from paying for any of it.
 *
 * The record is keyed by \`SampleId\`, so a sample the catalogue names and nobody shipped bytes for
 * is a compile error rather than a card that answers a press with a failure.
 */`;

async function writeGenerated(sizes: ReadonlyMap<string, number>): Promise<void> {
  const imports = SAMPLE_MATCHES.map(
    (sample, index) =>
      `import url${index} from '../../../../assets/samples/${sample.id}.disa.gz?url';`,
  );
  const rows = SAMPLE_MATCHES.map(
    (sample, index) =>
      `  '${sample.id}': { url: url${index}, byteLength: ${sizes.get(sample.id) ?? 0} },`,
  );

  const source = [
    '// Generated by `bun run samples:generate`. Do not edit.',
    ...imports,
    "import type { SampleId } from '../helpers/catalogue';",
    '',
    'export interface SampleAsset {',
    '  url: string;',
    '  /** The compressed size, which is what a reader is told a press will cost. */',
    '  byteLength: number;',
    '}',
    '',
    GENERATED_DOC,
    'export const SAMPLE_ASSETS: Record<SampleId, SampleAsset> = {',
    ...rows,
    '};',
    '',
  ].join('\n');

  await writeFile(GENERATED_PATH, source);
}

async function build(glue: ParserGlue, sample: SampleMatch, directory: string): Promise<number> {
  const demo = await parseFile(glue, `${directory}/${sample.sourceFile}`);

  if (demo.header.map !== sample.map) {
    throw new Error(`${sample.id} is ${demo.header.map}, and the catalogue names ${sample.map}`);
  }

  const container = flatten(encodeDemo(demo));
  const compressed = gzipSync(container, GZIP);
  await writeFile(`${ASSET_DIR}/${sample.id}.disa.gz`, compressed);

  const mib = (bytes: number) => (bytes / 1024 / 1024).toFixed(2);
  console.log(
    `${sample.id}: ${demo.events.rounds.length} rounds, ${mib(container.byteLength)} MiB -> ${mib(compressed.byteLength)} MiB gz`,
  );

  return compressed.byteLength;
}

const directory = process.env[SOURCE_ENV];
if (directory === undefined) {
  console.error(`${SOURCE_ENV} must name the directory holding the source .dem files`);
  process.exit(1);
}

const glue: ParserGlue = await import(GLUE_PATH);
await glue.default({ module_or_path: readFileSync(BINARY_PATH) });

const sizes = new Map<string, number>();
for (const sample of SAMPLE_MATCHES) sizes.set(sample.id, await build(glue, sample, directory));

await writeGenerated(sizes);
