import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { gunzipSync } from 'node:zlib';
import {
  mergeSpawns,
  roundStartPositions,
  type SideSpawns,
  TEAMS,
  type WorldPoint,
} from '@disa/demo-core';
import { decodeDemo } from '@disa/demo-store/codec';
import { SAMPLE_MATCHES } from '../../apps/web/src/core/samples/helpers/catalogue';
import { MAP_SPAWNS } from '../../packages/map-data/src/generated/spawns';

/**
 * Writes where each side stands when a round opens, per map, from parsed containers.
 *
 *     bun run spawns:generate
 *     DISALYTICS_SPAWN_DIR=<dir of .disa / .disa.gz containers> bun run spawns:generate
 *
 * The shipped samples are always read. Spots already in the committed file are kept, so a run over
 * one more map adds it without dropping the others, and a rerun over the same inputs changes
 * nothing. Containers are read, not `.dem` files — parse a demo into one with the app first.
 */
const OUTPUT_PATH = 'packages/map-data/src/generated/spawns.ts';
const SAMPLE_DIR = 'apps/web/assets/samples';
const EXTRA_ENV = 'DISALYTICS_SPAWN_DIR';

function containerPaths(): string[] {
  const paths = SAMPLE_MATCHES.map((sample) => `${SAMPLE_DIR}/${sample.id}.disa.gz`);
  const extra = process.env[EXTRA_ENV];
  if (extra !== undefined && extra !== '') {
    const names = readdirSync(extra)
      .filter((name) => name.endsWith('.disa') || name.endsWith('.disa.gz'))
      .sort();
    paths.push(...names.map((name) => join(extra, name)));
  }
  return paths;
}

function readContainer(path: string): Uint8Array {
  const bytes = readFileSync(path);
  return new Uint8Array(path.endsWith('.gz') ? gunzipSync(bytes) : bytes);
}

const pooled = new Map<string, Record<'CT' | 'T', WorldPoint[]>>();

function poolFor(map: string): Record<'CT' | 'T', WorldPoint[]> {
  const existing = pooled.get(map);
  if (existing !== undefined) return existing;
  const fresh: Record<'CT' | 'T', WorldPoint[]> = { CT: [], T: [] };
  pooled.set(map, fresh);
  return fresh;
}

for (const [map, spawns] of Object.entries(MAP_SPAWNS)) {
  const pool = poolFor(map);
  for (const side of TEAMS) pool[side].push(...spawns[side]);
}

for (const path of containerPaths()) {
  const demo = decodeDemo(readContainer(path));
  const found = roundStartPositions(demo);
  const pool = poolFor(demo.header.map);
  for (const side of TEAMS) pool[side].push(...found[side]);
  console.log(`${path}: ${demo.header.map}, ${demo.events.rounds.length} rounds`);
}

function emitPoints(points: readonly WorldPoint[]): string {
  return points.map((point) => `      { x: ${point.x}, y: ${point.y}, z: ${point.z} },\n`).join('');
}

const maps = [...pooled.keys()].sort();
const merged = new Map<string, SideSpawns>(
  maps.map((map) => {
    const pool = poolFor(map);
    return [map, { CT: mergeSpawns(pool.CT), T: mergeSpawns(pool.T) }];
  }),
);

const body = maps
  .map((map) => {
    const spawns = merged.get(map);
    if (spawns === undefined) return '';
    return `  ${map}: {\n    CT: [\n${emitPoints(spawns.CT)}    ],\n    T: [\n${emitPoints(spawns.T)}    ],\n  },\n`;
  })
  .join('');

writeFileSync(
  OUTPUT_PATH,
  `// Generated by \`bun run spawns:generate\` from parsed matches. Edit the inputs, not this file.

import type { SideSpawns } from '@disa/demo-core';

export const MAP_SPAWNS: Readonly<Record<string, SideSpawns>> = {
${body}};
`,
);

for (const map of maps) {
  const spawns = merged.get(map);
  console.log(`${map}: ${spawns?.CT.length ?? 0} CT, ${spawns?.T.length ?? 0} T`);
}
