import { readdir, readFile, writeFile } from 'node:fs/promises';
import { simplifyIconPath } from './weapon-icons/simplify';

const ASSET_DIR = 'apps/web/assets/weapon-icons';
const OUTPUT_PATH = 'apps/web/src/core/glyphs/generated/weapon-icons.ts';

/**
 * In the icons' own units, whose box is 32 tall. At the sizes §5.3 and §5.4 draw one — 10px of
 * height — this is a thirtieth of a pixel, and it takes the shipped table from 506 kB of Valve's
 * curves to 25 kB of polygons.
 */
const TOLERANCE = 0.3;
const DECIMALS = 1;

function fail(message: string): never {
  console.error(message);
  process.exit(1);
}

function attribute(source: string, name: string, id: string): string {
  const match = source.match(new RegExp(`\\s${name}="([^"]+)"`));
  if (match?.[1] === undefined) fail(`${id}: no ${name}`);

  return match[1];
}

function viewBox(source: string, id: string): { width: number; height: number } {
  const parts = attribute(source, 'viewBox', id).trim().split(/\s+/).map(Number);
  const [minX, minY, width, height] = parts;
  if (parts.length !== 4 || minX !== 0 || minY !== 0 || !width || !height)
    fail(`${id}: viewBox is not "0 0 <width> <height>"`);

  return { width, height };
}

async function readIcon(file: string): Promise<{ id: string; entry: string }> {
  const id = file.replace(/\.svg$/, '');
  const source = await readFile(`${ASSET_DIR}/${file}`, 'utf8');

  // One outline per icon is what makes the whole set one `d` and one fill rule. An asset with two
  // would silently lose everything after the first.
  const paths = source.match(/\sd="/g)?.length ?? 0;
  if (paths !== 1) fail(`${id}: ${paths} paths, expected 1`);

  const { width, height } = viewBox(source, id);
  const d = simplifyIconPath(attribute(source, 'd', id), TOLERANCE, DECIMALS);
  if (d === '') fail(`${id}: the outline simplified to nothing`);

  return {
    id,
    entry: `  ${id}: {\n    width: ${width},\n    height: ${height},\n    d: '${d}',\n  },`,
  };
}

const files = (await readdir(ASSET_DIR)).filter((file) => file.endsWith('.svg')).sort();
if (files.length === 0) fail(`${ASSET_DIR} holds no icons`);

const icons = await Promise.all(files.map(readIcon));

const output = `// Generated by \`bun run icons:generate\` from ${ASSET_DIR}.
// Valve owns these outlines; replace the assets and regenerate, never edit this file.

import type { WeaponIconId } from '@disa/demo-core';

export interface WeaponIcon {
  /**
   * The icon's own box. A caller sets the height and lets the width follow, which is how
   * Counter-Strike draws these and why a pistol is narrow rather than short.
   */
  readonly width: number;
  readonly height: number;
  /** Polygons, even-odd filled — simplified at ${TOLERANCE} of the box's 32 units. */
  readonly d: string;
}

/**
 * Every weapon \`@disa/demo-core\` can name an icon for. The record is keyed by \`WeaponIconId\`, so an
 * id the vocabulary tables name and nobody shipped is a compile error rather than an empty glyph.
 */
export const WEAPON_ICONS: Readonly<Record<WeaponIconId, WeaponIcon>> = {
${icons.map((icon) => icon.entry).join('\n')}
};
`;

await writeFile(OUTPUT_PATH, output);
console.log(`${OUTPUT_PATH}: ${icons.length} icons, ${output.length} bytes`);
