import { sampleAt } from '@disa/demo-core';

export const OUTPUT_PATH = 'apps/web/src/features/library/generated/reel.ts';

/** One grenade as the reel records it: where it went off, and the window it is drawn in. */
export interface ReelGrenadeRow {
  type: string;
  detonateFrame: number;
  endFrame: number;
  x: number;
  y: number;
}

/** Everything `build.ts` decided, in the order the module states it. */
export interface ReelCut {
  map: string;
  round: number;
  hz: number;
  frameCount: number;
  stillFrame: number;
  slotCount: number;
  quantOrigin: number;
  quantUnits: number;
  positions: Uint16Array;
  alive: Uint8Array;
  grenades: readonly ReelGrenadeRow[];
}

/**
 * The bulk of the reel: a running difference along each player's own track.
 *
 * **A walk is small numbers, and small numbers are what gzip is good at** — a step at 4 Hz is tens
 * of units where a position is thousands. Measured on this round at this quantisation, the deltas
 * as a plain integer array gzip to **3.51 kB** against **3.77 kB** for the same numbers base64'd,
 * and the array needs no `atob` and no byte-plane split on the way back in: `decodeReel` is a
 * running sum and nothing else. The absolute positions, undifferenced, gzip to 6.28 kB.
 */
function packPositions(values: Uint16Array, seriesCount: number, frameCount: number): number[] {
  const deltas: number[] = [];

  for (let series = 0; series < seriesCount; series += 1) {
    const base = series * frameCount;
    let previous = 0;

    for (let frame = 0; frame < frameCount; frame += 1) {
      const value = sampleAt(values, base + frame);

      deltas.push(value - previous);
      previous = value;
    }
  }

  return deltas;
}

const GENERATED_DOC = `/**
 * One round of IEM Atlanta 2026, cut from the sample container this build already ships and small
 * enough to sit inside the bundle. Written by \`bun run reel:generate\`, held to the container it came
 * from by \`bun run reel:check\`.
 *
 * **It is in the bundle rather than beside it on purpose.** #330's rule for this screen is that
 * nothing is fetched before a reader presses something, and an asset imported with \`?url\` is a
 * request — so the reel is a module, and the way in still reaches the network for nothing at all.
 */`;
/**
 * The formatter's own answer for the file, rather than this script's guess at it.
 *
 * A generated file is checked by `bun run check` like any other, and the reel's bulk is an array of
 * four thousand numbers — whose wrapping is a fill algorithm, not a rule anything here should be
 * reimplementing. Asking Biome means a version of it that reflows arrays differently changes this
 * file the same way it changes a hand-written one, and `reel:check` stays a true comparison because
 * both sides come through here.
 */
function formatted(source: string): string {
  const run = Bun.spawnSync(
    ['bunx', '--bun', 'biome', 'format', `--stdin-file-path=${OUTPUT_PATH}`],
    {
      stdin: Buffer.from(source),
    },
  );

  if (run.exitCode !== 0) {
    throw new Error(`biome could not format the reel: ${run.stderr.toString()}`);
  }

  return run.stdout.toString();
}
/** The generated module's whole text, formatted the way the repository's own check wants it. */
export function emitReel(cut: ReelCut): string {
  const grenades = cut.grenades.map(
    (row) =>
      `    { type: '${row.type}', detonateFrame: ${row.detonateFrame}, endFrame: ${row.endFrame}, x: ${row.x}, y: ${row.y} },`,
  );

  return formatted(
    [
      '// Generated by `bun run reel:generate`. Do not edit.',
      "import type { ReelSource } from '../helpers/reel';",
      '',
      GENERATED_DOC,
      'export const WAY_IN_REEL: ReelSource = {',
      `  map: '${cut.map}',`,
      `  round: ${cut.round},`,
      `  hz: ${cut.hz},`,
      `  frameCount: ${cut.frameCount},`,
      `  stillFrame: ${cut.stillFrame},`,
      `  slotCount: ${cut.slotCount},`,
      `  quantOrigin: ${cut.quantOrigin},`,
      `  quantUnits: ${cut.quantUnits},`,
      `  positions: [${packPositions(cut.positions, cut.slotCount * 2, cut.frameCount).join(', ')}],`,
      `  alive: [${[...cut.alive].join(', ')}],`,
      '  grenades: [',
      ...grenades,
      '  ],',
      '};',
      '',
    ].join('\n'),
  );
}
