import type { MapId } from './generated/overviews';
import { isMapId } from './transform';
import type { NavGrid, NavGridData, NavLevel } from './types';

/**
 * Each map's traced floor loads on demand into its own chunk, so a map nobody draws a route on
 * costs no bytes. Generated by `bun run navgrid:generate`; the files hold no logic.
 */
const NAV_GRIDS: Readonly<Record<MapId, () => Promise<{ readonly NAV_GRID: NavGridData }>>> = {
  de_ancient: () => import('./generated/navgrids/de_ancient'),
  de_anubis: () => import('./generated/navgrids/de_anubis'),
  de_dust2: () => import('./generated/navgrids/de_dust2'),
  de_inferno: () => import('./generated/navgrids/de_inferno'),
  de_mirage: () => import('./generated/navgrids/de_mirage'),
  de_nuke: () => import('./generated/navgrids/de_nuke'),
  de_overpass: () => import('./generated/navgrids/de_overpass'),
};

const BASE64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';

/** Standard base64 to bytes; `atob` is a browser/Node global the package's `lib` does not declare. */
function decodeBase64(text: string): Uint8Array {
  const clean = text.replace(/=+$/, '');
  const bytes = new Uint8Array(Math.floor((clean.length * 6) / 8));
  let buffer = 0;
  let bits = 0;
  let at = 0;

  for (const char of clean) {
    buffer = (buffer << 6) | BASE64.indexOf(char);
    bits += 6;
    if (bits >= 8) {
      bits -= 8;
      bytes[at++] = (buffer >> bits) & 0xff;
    }
  }

  return bytes;
}

/** Unpack one level: bit `i` of the row-major grid, most significant bit first. */
export function unpackNavLevel(packed: string, size: number, cell: number): NavLevel {
  const bytes = decodeBase64(packed);
  const walkable = new Uint8Array(size * size);
  for (let i = 0; i < walkable.length; i++) {
    walkable[i] = ((bytes[i >> 3] ?? 0) >> (7 - (i & 7))) & 1;
  }
  return { cell, size, walkable };
}

export function unpackNavGrid(map: string, data: NavGridData): NavGrid {
  return { map, levels: data.levels.map((level) => unpackNavLevel(level, data.size, data.cell)) };
}

const loaded = new Map<string, Promise<NavGrid | undefined>>();

/**
 * The walkable grids of a map in the pool, or `undefined` for one outside it (a workshop map has
 * no traced radar). Traced from the radar picture — a named approximation, not Valve's nav mesh.
 */
export function loadMapNavGrid(map: string): Promise<NavGrid | undefined> {
  if (!isMapId(map)) return Promise.resolve(undefined);

  let pending = loaded.get(map);
  if (pending === undefined) {
    pending = NAV_GRIDS[map]().then(({ NAV_GRID }) => unpackNavGrid(map, NAV_GRID));
    pending.catch(() => loaded.delete(map));
    loaded.set(map, pending);
  }
  return pending;
}
